In [1]:
import pandas as pd
import numpy as np

import os
import time
from time import sleep
from pathlib import Path

from nba_api.stats.endpoints import (
    leaguedashplayerstats,
    leaguedashptstats,
    leaguedashplayershotlocations,
    leaguehustlestatsplayer
)
from nba_api.stats.static import players as nba_players, teams as nba_teams

SEASON = "2025-26"
SEASON_TYPE = "Regular Season"

In [2]:
RAW_DATA_DIR = Path("C:\\Users\\aabre\\Documents\\data-science-projects\\nba-player-archetype-clustering\\data\\raw\\2025_26")
RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)
RAW_DATA_DIR

WindowsPath('C:/Users/aabre/Documents/data-science-projects/nba-player-archetype-clustering/data/raw/2025_26')

In [3]:
def get_base_stats(season = SEASON):
    base_stats_df = leaguedashplayerstats.LeagueDashPlayerStats(
        measure_type_detailed_defense="Base",
        per_mode_detailed="Totals",
        season=season,
        season_type_all_star=SEASON_TYPE,
        timeout=60
    ).get_data_frames()[0]
    base_stats_df.to_csv(RAW_DATA_DIR / f"base_stats.csv", index=False)
    return base_stats_df.columns.tolist(), base_stats_df.head()

get_base_stats()

(['PLAYER_ID',
  'PLAYER_NAME',
  'NICKNAME',
  'TEAM_ID',
  'TEAM_ABBREVIATION',
  'AGE',
  'GP',
  'W',
  'L',
  'W_PCT',
  'MIN',
  'FGM',
  'FGA',
  'FG_PCT',
  'FG3M',
  'FG3A',
  'FG3_PCT',
  'FTM',
  'FTA',
  'FT_PCT',
  'OREB',
  'DREB',
  'REB',
  'AST',
  'TOV',
  'STL',
  'BLK',
  'BLKA',
  'PF',
  'PFD',
  'PTS',
  'PLUS_MINUS',
  'NBA_FANTASY_PTS',
  'DD2',
  'TD3',
  'WNBA_FANTASY_PTS',
  'FP_HIGH_SCORE',
  'GP_RANK',
  'W_RANK',
  'L_RANK',
  'W_PCT_RANK',
  'MIN_RANK',
  'FGM_RANK',
  'FGA_RANK',
  'FG_PCT_RANK',
  'FG3M_RANK',
  'FG3A_RANK',
  'FG3_PCT_RANK',
  'FTM_RANK',
  'FTA_RANK',
  'FT_PCT_RANK',
  'OREB_RANK',
  'DREB_RANK',
  'REB_RANK',
  'AST_RANK',
  'TOV_RANK',
  'STL_RANK',
  'BLK_RANK',
  'BLKA_RANK',
  'PF_RANK',
  'PFD_RANK',
  'PTS_RANK',
  'PLUS_MINUS_RANK',
  'NBA_FANTASY_PTS_RANK',
  'DD2_RANK',
  'TD3_RANK',
  'WNBA_FANTASY_PTS_RANK',
  'FP_HIGH_SCORE_RANK',
  'TEAM_COUNT'],
    PLAYER_ID    PLAYER_NAME NICKNAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
 0    1630639    A.J. Lawson     A.J.  1610612761               TOR  25.0  24
 1    1631260       AJ Green       AJ  1610612749               MIL  26.0  78
 2    1642358     AJ Johnson       AJ  1610612742               DAL  21.0  48
 3     203932   Aaron Gordon    Aaron  1610612743               DEN  30.0  36
 4    1628988  Aaron Holiday    Aaron  1610612745               HOU  29.0  57

     W   L  W_PCT  ...  PF_RANK  PFD_RANK  PTS_RANK  PLUS_MINUS_RANK  \
 0  12  12  0.500  ...      142       443       438              290
 1  31  47  0.397  ...      540       229       126              496
 2   9  39  0.188  ...      158       384       400              394
 3  27   9  0.750  ...      242       143       197               48
 4  38  19  0.667  ...      274       323       321               99

    NBA_FANTASY_PTS_RANK  DD2_RANK  TD3_RANK  WNBA_FANTASY_PTS_RANK  \
 0                   450       284        38                    449
 1                   175       284        38                    139
 2                   414       284        38                    413
 3                   247       114        38                    241
 4                   354       284        38                    348

    FP_HIGH_SCORE_RANK  TEAM_COUNT
 0                 454           1
 1                 167           1
 2                 412           2
 3                 250           1
 4                 352           1

 [5 rows x 69 columns])

In [4]:
def get_advanced_stats(season = SEASON):
    advanced_stats_df = leaguedashplayerstats.LeagueDashPlayerStats(
        measure_type_detailed_defense="Advanced",
        per_mode_detailed="Totals",
        season=season,
        season_type_all_star=SEASON_TYPE,
        timeout=60
    ).get_data_frames()[0]
    advanced_stats_df.to_csv(RAW_DATA_DIR / f"advanced_stats.csv", index=False)
    return advanced_stats_df.columns.tolist(), advanced_stats_df.head()

get_advanced_stats()

(['PLAYER_ID',
  'PLAYER_NAME',
  'NICKNAME',
  'TEAM_ID',
  'TEAM_ABBREVIATION',
  'AGE',
  'GP',
  'W',
  'L',
  'W_PCT',
  'MIN',
  'E_OFF_RATING',
  'OFF_RATING',
  'sp_work_OFF_RATING',
  'E_DEF_RATING',
  'DEF_RATING',
  'sp_work_DEF_RATING',
  'E_NET_RATING',
  'NET_RATING',
  'sp_work_NET_RATING',
  'AST_PCT',
  'AST_TO',
  'AST_RATIO',
  'OREB_PCT',
  'DREB_PCT',
  'REB_PCT',
  'TM_TOV_PCT',
  'E_TOV_PCT',
  'EFG_PCT',
  'TS_PCT',
  'USG_PCT',
  'E_USG_PCT',
  'E_PACE',
  'PACE',
  'PACE_PER40',
  'sp_work_PACE',
  'PIE',
  'POSS',
  'FGM',
  'FGA',
  'FGM_PG',
  'FGA_PG',
  'FG_PCT',
  'GP_RANK',
  'W_RANK',
  'L_RANK',
  'W_PCT_RANK',
  'MIN_RANK',
  'E_OFF_RATING_RANK',
  'OFF_RATING_RANK',
  'sp_work_OFF_RATING_RANK',
  'E_DEF_RATING_RANK',
  'DEF_RATING_RANK',
  'sp_work_DEF_RATING_RANK',
  'E_NET_RATING_RANK',
  'NET_RATING_RANK',
  'sp_work_NET_RATING_RANK',
  'AST_PCT_RANK',
  'AST_TO_RANK',
  'AST_RATIO_RANK',
  'OREB_PCT_RANK',
  'DREB_PCT_RANK',
  'REB_PCT_RANK',
  'TM_TOV_PCT_RANK',
  'E_TOV_PCT_RANK',
  'EFG_PCT_RANK',
  'TS_PCT_RANK',
  'USG_PCT_RANK',
  'E_USG_PCT_RANK',
  'E_PACE_RANK',
  'PACE_RANK',
  'sp_work_PACE_RANK',
  'PIE_RANK',
  'FGM_RANK',
  'FGA_RANK',
  'FGM_PG_RANK',
  'FGA_PG_RANK',
  'FG_PCT_RANK',
  'TEAM_COUNT'],
    PLAYER_ID    PLAYER_NAME NICKNAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
 0    1630639    A.J. Lawson     A.J.  1610612761               TOR  25.0  24
 1    1631260       AJ Green       AJ  1610612749               MIL  26.0  78
 2    1642358     AJ Johnson       AJ  1610612742               DAL  21.0  48
 3     203932   Aaron Gordon    Aaron  1610612743               DEN  30.0  36
 4    1628988  Aaron Holiday    Aaron  1610612745               HOU  29.0  57

     W   L  W_PCT  ...  E_PACE_RANK  PACE_RANK  sp_work_PACE_RANK  PIE_RANK  \
 0  12  12  0.500  ...          506        456                456       268
 1  31  47  0.397  ...          415        467                467       497
 2   9  39  0.188  ...          293        270                270       544
 3  27   9  0.750  ...          394        426                426       104
 4  38  19  0.667  ...          451        445                445       468

    FGM_RANK  FGA_RANK  FGM_PG_RANK  FGA_PG_RANK  FG_PCT_RANK  TEAM_COUNT
 0       443       447          454          442          363           1
 1       149       129          237          211          403           1
 2       401       370          486          421          552           2
 3       215       229          101          119          168           1
 4       332       316          402          385          434           1

 [5 rows x 79 columns])

In [5]:
def get_scoring_splits(season = SEASON):
    scoring_splits_df = leaguedashplayerstats.LeagueDashPlayerStats(
        measure_type_detailed_defense="Scoring",
        per_mode_detailed="Totals",
        season=season,
        season_type_all_star=SEASON_TYPE,
        timeout=60
    ).get_data_frames()[0]
    scoring_splits_df.to_csv(RAW_DATA_DIR / f"scoring_splits.csv", index=False)
    return scoring_splits_df.columns.tolist(), scoring_splits_df.head()

get_scoring_splits()

(['PLAYER_ID',
  'PLAYER_NAME',
  'NICKNAME',
  'TEAM_ID',
  'TEAM_ABBREVIATION',
  'AGE',
  'GP',
  'W',
  'L',
  'W_PCT',
  'MIN',
  'PCT_FGA_2PT',
  'PCT_FGA_3PT',
  'PCT_PTS_2PT',
  'PCT_PTS_2PT_MR',
  'PCT_PTS_3PT',
  'PCT_PTS_FB',
  'PCT_PTS_FT',
  'PCT_PTS_OFF_TOV',
  'PCT_PTS_PAINT',
  'PCT_AST_2PM',
  'PCT_UAST_2PM',
  'PCT_AST_3PM',
  'PCT_UAST_3PM',
  'PCT_AST_FGM',
  'PCT_UAST_FGM',
  'FGM',
  'FGA',
  'FG_PCT',
  'GP_RANK',
  'W_RANK',
  'L_RANK',
  'W_PCT_RANK',
  'MIN_RANK',
  'PCT_FGA_2PT_RANK',
  'PCT_FGA_3PT_RANK',
  'PCT_PTS_2PT_RANK',
  'PCT_PTS_2PT_MR_RANK',
  'PCT_PTS_3PT_RANK',
  'PCT_PTS_FB_RANK',
  'PCT_PTS_FT_RANK',
  'PCT_PTS_OFF_TOV_RANK',
  'PCT_PTS_PAINT_RANK',
  'PCT_AST_2PM_RANK',
  'PCT_UAST_2PM_RANK',
  'PCT_AST_3PM_RANK',
  'PCT_UAST_3PM_RANK',
  'PCT_AST_FGM_RANK',
  'PCT_UAST_FGM_RANK',
  'FGM_RANK',
  'FGA_RANK',
  'FG_PCT_RANK',
  'TEAM_COUNT'],
    PLAYER_ID    PLAYER_NAME NICKNAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
 0    1630639    A.J. Lawson     A.J.  1610612761               TOR  25.0  24
 1    1631260       AJ Green       AJ  1610612749               MIL  26.0  78
 2    1642358     AJ Johnson       AJ  1610612742               DAL  21.0  48
 3     203932   Aaron Gordon    Aaron  1610612743               DEN  30.0  36
 4    1628988  Aaron Holiday    Aaron  1610612745               HOU  29.0  57

     W   L  W_PCT  ...  PCT_AST_2PM_RANK  PCT_UAST_2PM_RANK  PCT_AST_3PM_RANK  \
 0  12  12  0.500  ...                21                554                 1
 1  31  47  0.397  ...               162                410               287
 2   9  39  0.188  ...               495                 79               437
 3  27   9  0.750  ...               243                332               372
 4  38  19  0.667  ...               554                 21               261

    PCT_UAST_3PM_RANK  PCT_AST_FGM_RANK  PCT_UAST_FGM_RANK  FGM_RANK  FGA_RANK  \
 0                368                25                553       443       447
 1                230                47                531       149       129
 2                 75               525                 53       401       370
 3                145               280                298       215       229
 4                256               307                271       332       316

    FG_PCT_RANK  TEAM_COUNT
 0          363           1
 1          403           1
 2          552           2
 3          168           1
 4          434           1

 [5 rows x 53 columns])

In [6]:
def get_usage_stats(season = SEASON):
    usage_stats_df = leaguedashplayerstats.LeagueDashPlayerStats(
        measure_type_detailed_defense="Usage",
        per_mode_detailed="Totals",
        season=season,
        season_type_all_star=SEASON_TYPE,
        timeout=60
    ).get_data_frames()[0]
    usage_stats_df.to_csv(RAW_DATA_DIR / f"usage_stats.csv", index=False)
    return usage_stats_df.columns.tolist(), usage_stats_df.head()

get_usage_stats()

(['PLAYER_ID',
  'PLAYER_NAME',
  'NICKNAME',
  'TEAM_ID',
  'TEAM_ABBREVIATION',
  'AGE',
  'GP',
  'W',
  'L',
  'W_PCT',
  'MIN',
  'USG_PCT',
  'PCT_FGM',
  'PCT_FGA',
  'PCT_FG3M',
  'PCT_FG3A',
  'PCT_FTM',
  'PCT_FTA',
  'PCT_OREB',
  'PCT_DREB',
  'PCT_REB',
  'PCT_AST',
  'PCT_TOV',
  'PCT_STL',
  'PCT_BLK',
  'PCT_BLKA',
  'PCT_PF',
  'PCT_PFD',
  'PCT_PTS',
  'GP_RANK',
  'W_RANK',
  'L_RANK',
  'W_PCT_RANK',
  'MIN_RANK',
  'USG_PCT_RANK',
  'PCT_FGM_RANK',
  'PCT_FGA_RANK',
  'PCT_FG3M_RANK',
  'PCT_FG3A_RANK',
  'PCT_FTM_RANK',
  'PCT_FTA_RANK',
  'PCT_OREB_RANK',
  'PCT_DREB_RANK',
  'PCT_REB_RANK',
  'PCT_AST_RANK',
  'PCT_TOV_RANK',
  'PCT_STL_RANK',
  'PCT_BLK_RANK',
  'PCT_BLKA_RANK',
  'PCT_PF_RANK',
  'PCT_PFD_RANK',
  'PCT_PTS_RANK',
  'TEAM_COUNT'],
    PLAYER_ID    PLAYER_NAME NICKNAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP  \
 0    1630639    A.J. Lawson     A.J.  1610612761               TOR  25.0  24
 1    1631260       AJ Green       AJ  1610612749               MIL  26.0  78
 2    1642358     AJ Johnson       AJ  1610612742               DAL  21.0  48
 3     203932   Aaron Gordon    Aaron  1610612743               DEN  30.0  36
 4    1628988  Aaron Holiday    Aaron  1610612745               HOU  29.0  57

     W   L  W_PCT  ...  PCT_REB_RANK  PCT_AST_RANK  PCT_TOV_RANK  PCT_STL_RANK  \
 0  12  12  0.500  ...           181           565            92            32
 1  31  47  0.397  ...           527           400           103           523
 2   9  39  0.188  ...           464           177           386           405
 3  27   9  0.750  ...           196           307           327           450
 4  38  19  0.667  ...           570           305           279           258

    PCT_BLK_RANK  PCT_BLKA_RANK  PCT_PF_RANK  PCT_PFD_RANK  PCT_PTS_RANK  \
 0           208            441          475           375           204
 1           503             65          245           494           403
 2           465            545          146           327           377
 3           320            174          161           101           123
 4           481            136          345           397           327

    TEAM_COUNT
 0           1
 1           1
 2           2
 3           1
 4           1

 [5 rows x 53 columns])

In [8]:
TRACKING_STATS = ["Passing", "Rebounding", "SpeedDistance", "Possessions", "Defense", "Drives", 
                  "CatchShoot", "PullUpShot", "PostTouch", "ElbowTouch", "PaintTouch", "Efficiency"]
def get_tracking_stats(measure_type = TRACKING_STATS, season = SEASON):
    for measure in measure_type:
        print(f"Collecting {measure} stats...")
        try:
            tracking_stats_df = leaguedashptstats.LeagueDashPtStats(
                pt_measure_type=measure,
                player_or_team="Player",
                per_mode_simple="Totals",
                season=season,
                season_type_all_star=SEASON_TYPE,
                timeout=60
            ).get_data_frames()[0]
            tracking_stats_df.to_csv(RAW_DATA_DIR / f"{measure.lower()}_stats.csv", index=False)
            print(f"Saved {measure.lower()}_stats.csv")
            sleep(1.5)
        except Exception as e:
            print(f"Error occurred while collecting {measure} stats: {e}")
    return [f"{measure.lower()}_stats.csv" for measure in measure_type]

get_tracking_stats()

Collecting Passing stats...
Saved passing_stats.csv
Collecting Rebounding stats...
Saved rebounding_stats.csv
Collecting SpeedDistance stats...
Saved speeddistance_stats.csv
Collecting Possessions stats...
Saved possessions_stats.csv
Collecting Defense stats...
Saved defense_stats.csv
Collecting Drives stats...
Saved drives_stats.csv
Collecting CatchShoot stats...
Saved catchshoot_stats.csv
Collecting PullUpShot stats...
Saved pullupshot_stats.csv
Collecting PostTouch stats...
Saved posttouch_stats.csv
Collecting ElbowTouch stats...
Saved elbowtouch_stats.csv
Collecting PaintTouch stats...
Saved painttouch_stats.csv
Collecting Efficiency stats...
Saved efficiency_stats.csv

['passing_stats.csv',
 'rebounding_stats.csv',
 'speeddistance_stats.csv',
 'possessions_stats.csv',
 'defense_stats.csv',
 'drives_stats.csv',
 'catchshoot_stats.csv',
 'pullupshot_stats.csv',
 'posttouch_stats.csv',
 'elbowtouch_stats.csv',
 'painttouch_stats.csv',
 'efficiency_stats.csv']

In [ ]:
def get_shot_location_stats(season = SEASON):
    shot_location_stats_df = leaguedashplayershotlocations.LeagueDashPlayerShotLocations(
        measure_type_simple="Base",
        per_mode_detailed="Totals",
        distance_range="By Zone",
        season=season,
        season_type_all_star=SEASON_TYPE,
        timeout=60
    ).get_data_frames()[0]
    shot_location_stats_df.to_csv(RAW_DATA_DIR / f"shot_location_stats.csv", index=False)
    return shot_location_stats_df.columns.tolist(), shot_location_stats_df.head()

get_shot_location_stats()

([('', np.str_('PLAYER_ID')),
  ('', np.str_('PLAYER_NAME')),
  ('', np.str_('TEAM_ID')),
  ('', np.str_('TEAM_ABBREVIATION')),
  ('', np.str_('AGE')),
  ('', np.str_('NICKNAME')),
  (np.str_('Restricted Area'), np.str_('FGM')),
  (np.str_('Restricted Area'), np.str_('FGA')),
  (np.str_('Restricted Area'), np.str_('FG_PCT')),
  (np.str_('In The Paint (Non-RA)'), np.str_('FGM')),
  (np.str_('In The Paint (Non-RA)'), np.str_('FGA')),
  (np.str_('In The Paint (Non-RA)'), np.str_('FG_PCT')),
  (np.str_('Mid-Range'), np.str_('FGM')),
  (np.str_('Mid-Range'), np.str_('FGA')),
  (np.str_('Mid-Range'), np.str_('FG_PCT')),
  (np.str_('Left Corner 3'), np.str_('FGM')),
  (np.str_('Left Corner 3'), np.str_('FGA')),
  (np.str_('Left Corner 3'), np.str_('FG_PCT')),
  (np.str_('Right Corner 3'), np.str_('FGM')),
  (np.str_('Right Corner 3'), np.str_('FGA')),
  (np.str_('Right Corner 3'), np.str_('FG_PCT')),
  (np.str_('Above the Break 3'), np.str_('FGM')),
  (np.str_('Above the Break 3'), np.str_('FGA')),
  (np.str_('Above the Break 3'), np.str_('FG_PCT')),
  (np.str_('Backcourt'), np.str_('FGM')),
  (np.str_('Backcourt'), np.str_('FGA')),
  (np.str_('Backcourt'), np.str_('FG_PCT')),
  (np.str_('Corner 3'), np.str_('FGM')),
  (np.str_('Corner 3'), np.str_('FGA')),
  (np.str_('Corner 3'), np.str_('FG_PCT'))],
 SHOT_CATEGORY                                                               \
 columns       PLAYER_ID    PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE
 0               1630639    A.J. Lawson  1610612761               TOR  25.0
 1               1631260       AJ Green  1610612749               MIL  26.0
 2               1642358     AJ Johnson  1610612742               DAL  21.0
 3                203932   Aaron Gordon  1610612743               DEN  30.0
 4               1628988  Aaron Holiday  1610612745               HOU  29.0

 SHOT_CATEGORY          Restricted Area             In The Paint (Non-RA)  ...  \
 columns       NICKNAME             FGM  FGA FG_PCT                   FGM  ...
 0                 A.J.              14   27  0.519                     1  ...
 1                   AJ              11   19  0.579                    10  ...
 2                   AJ              33   77  0.429                    12  ...
 3                Aaron              97  129  0.752                    20  ...
 4                Aaron              13   22  0.591                    21  ...

 SHOT_CATEGORY Right Corner 3 Above the Break 3             Backcourt       \
 columns               FG_PCT               FGM  FGA FG_PCT       FGM  FGA
 0                      0.364                 5   13  0.385       0.0  0.0
 1                      0.479               158  402  0.393       0.0  0.0
 2                      0.286                 9   46  0.196       0.0  0.0
 3                      0.524                41  111  0.369       0.0  0.0
 4                      0.455                42  117  0.359       0.0  0.0

 SHOT_CATEGORY        Corner 3
 columns       FG_PCT      FGM  FGA FG_PCT
 0                0.0       14   32  0.438
 1                0.0       74  152  0.487
 2                0.0        3   11  0.273
 3                0.0       20   46  0.435
 4                0.0       25   53  0.472

 [5 rows x 30 columns])

In [4]:
def get_hustle_stats(season = SEASON):
    hustle_stats_df = leaguehustlestatsplayer.LeagueHustleStatsPlayer(
        season=season,
        season_type_all_star=SEASON_TYPE,
        per_mode_time="Totals",
        timeout=60
    ).get_data_frames()[0]
    hustle_stats_df.to_csv(RAW_DATA_DIR / f"hustle_stats.csv", index=False)
    return hustle_stats_df.columns.tolist(), hustle_stats_df.head()

get_hustle_stats()

(['PLAYER_ID',
  'PLAYER_NAME',
  'TEAM_ID',
  'TEAM_ABBREVIATION',
  'AGE',
  'G',
  'MIN',
  'CONTESTED_SHOTS',
  'CONTESTED_SHOTS_2PT',
  'CONTESTED_SHOTS_3PT',
  'DEFLECTIONS',
  'CHARGES_DRAWN',
  'SCREEN_ASSISTS',
  'SCREEN_AST_PTS',
  'OFF_LOOSE_BALLS_RECOVERED',
  'DEF_LOOSE_BALLS_RECOVERED',
  'LOOSE_BALLS_RECOVERED',
  'PCT_LOOSE_BALLS_RECOVERED_OFF',
  'PCT_LOOSE_BALLS_RECOVERED_DEF',
  'OFF_BOXOUTS',
  'DEF_BOXOUTS',
  'BOX_OUT_PLAYER_TEAM_REBS',
  'BOX_OUT_PLAYER_REBS',
  'BOX_OUTS',
  'PCT_BOX_OUTS_OFF',
  'PCT_BOX_OUTS_DEF',
  'PCT_BOX_OUTS_TEAM_REB',
  'PCT_BOX_OUTS_REB'],
    PLAYER_ID    PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE   G     MIN  \
 0    1630639    A.J. Lawson  1610612761               TOR  25.0  16   173.0
 1    1631260       AJ Green  1610612749               MIL  26.0  78  2270.0
 2    1642358     AJ Johnson  1610612742               DAL  21.0  31   380.0
 3     203932   Aaron Gordon  1610612743               DEN  30.0  36  1005.0
 4    1628988  Aaron Holiday  1610612745               HOU  29.0  49   738.0

    CONTESTED_SHOTS  CONTESTED_SHOTS_2PT  CONTESTED_SHOTS_3PT  ...  \
 0               20                   12                    8  ...
 1              306                  172                  134  ...
 2               64                   34                   30  ...
 3              102                   67                   35  ...
 4              102                   49                   53  ...

    PCT_LOOSE_BALLS_RECOVERED_DEF  OFF_BOXOUTS  DEF_BOXOUTS  \
 0                          1.000            0            6
 1                          0.722            0           36
 2                          0.000            0            1
 3                          0.600            4           10
 4                          0.800            0            7

    BOX_OUT_PLAYER_TEAM_REBS  BOX_OUT_PLAYER_REBS  BOX_OUTS  PCT_BOX_OUTS_OFF  \
 0                         6                    3         6             0.000
 1                        36                    9        36             0.000
 2                         1                    0         1             0.000
 3                        14                   11        14             0.286
 4                         7                    2         7             0.000

    PCT_BOX_OUTS_DEF  PCT_BOX_OUTS_TEAM_REB  PCT_BOX_OUTS_REB
 0             1.000                    1.0             0.500
 1             1.000                    1.0             0.250
 2             1.000                    1.0             0.000
 3             0.714                    1.0             0.786
 4             1.000                    1.0             0.286

 [5 rows x 28 columns])

In [5]:
datasets = {}
for file in RAW_DATA_DIR.glob("*.csv"):
    dataset_name = file.stem
    if dataset_name.startswith("0"):  # Skips our inventory/summary files
            continue
    datasets[dataset_name] = pd.read_csv(file)

In [11]:
shot_location_columns = [
    "PLAYER_ID",
    "PLAYER_NAME",
    "TEAM_ID",
    "TEAM_ABBREVIATION",
    "AGE",
    "NICKNAME",
    "RA_FGM",
    "RA_FGA",
    "RA_FG_PCT",
    "PAINT_NON_RA_FGM",
    "PAINT_NON_RA_FGA",
    "PAINT_NON_RA_FG_PCT",
    "MIDRANGE_FGM",
    "MIDRANGE_FGA",
    "MIDRANGE_FG_PCT",
    "LEFT_CORNER_3_FGM",
    "LEFT_CORNER_3_FGA",
    "LEFT_CORNER_3_FG_PCT",
    "RIGHT_CORNER_3_FGM",
    "RIGHT_CORNER_3_FGA",
    "RIGHT_CORNER_3_FG_PCT",
    "ABOVE_BREAK_3_FGM",
    "ABOVE_BREAK_3_FGA",
    "ABOVE_BREAK_3_FG_PCT",
    "BACKCOURT_FGM",
    "BACKCOURT_FGA",
    "BACKCOURT_FG_PCT",
    "CORNER_3_FGM",
    "CORNER_3_FGA",
    "CORNER_3_PCT"
]

shot_location_clean = datasets["shot_location_stats"].copy()
shot_location_clean.columns = shot_location_columns
shot_location_clean = shot_location_clean.iloc[1:]
datasets["shot_location_stats"] = shot_location_clean

shot_location_clean.to_csv(RAW_DATA_DIR / f"shot_location_stats.csv", index=False)
shot_location_clean.head()

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,NICKNAME,RA_FGM,RA_FGA,RA_FG_PCT,PAINT_NON_RA_FGM,...,RIGHT_CORNER_3_FG_PCT,ABOVE_BREAK_3_FGM,ABOVE_BREAK_3_FGA,ABOVE_BREAK_3_FG_PCT,BACKCOURT_FGM,BACKCOURT_FGA,BACKCOURT_FG_PCT,CORNER_3_FGM,CORNER_3_FGA,CORNER_3_PCT
1,1630639,A.J. Lawson,1610612761,TOR,25.0,A.J.,14,27,0.519,1,...,0.364,5,13,0.385,0.0,0.0,0.0,14,32,0.438
2,1631260,AJ Green,1610612749,MIL,26.0,AJ,11,19,0.579,10,...,0.479,158,402,0.393,0.0,0.0,0.0,74,152,0.487
3,1642358,AJ Johnson,1610612742,DAL,21.0,AJ,33,77,0.429,12,...,0.286,9,46,0.196,0.0,0.0,0.0,3,11,0.273
4,203932,Aaron Gordon,1610612743,DEN,30.0,Aaron,97,129,0.752,20,...,0.524,41,111,0.369,0.0,0.0,0.0,20,46,0.435
5,1628988,Aaron Holiday,1610612745,HOU,29.0,Aaron,13,22,0.591,21,...,0.455,42,117,0.359,0.0,0.0,0.0,25,53,0.472

In [12]:
dataset_inventory = {name: df.shape for name, df in datasets.items()}
dataset_inventory_df = pd.DataFrame.from_dict(dataset_inventory, orient='index', columns=['Rows', 'Columns'])
dataset_inventory_df

                     Rows  Columns
advanced_stats        582       79
base_stats            582       69
catchshoot_stats      582       16
defense_stats         582       14
drives_stats          582       25
efficiency_stats      582       22
elbowtouch_stats      582       26
hustle_stats          581       28
painttouch_stats      582       26
passing_stats         582       18
possessions_stats     582       21
posttouch_stats       582       26
pullupshot_stats      582       16
rebounding_stats      578       35
scoring_splits        582       53
shot_location_stats   582       30
speeddistance_stats   582       15
usage_stats           582       53

In [13]:
column_inventory = {name: df.columns.tolist() for name, df in datasets.items()}
column_inventory_df = pd.DataFrame.from_dict(column_inventory, orient='index')
column_inventory_df

,0,1,2,3,4,5,6,7,8,9,...,69,70,71,72,73,74,75,76,77,78
advanced_stats,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,E_PACE_RANK,PACE_RANK,sp_work_PACE_RANK,PIE_RANK,FGM_RANK,FGA_RANK,FGM_PG_RANK,FGA_PG_RANK,FG_PCT_RANK,TEAM_COUNT
base_stats,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
catchshoot_stats,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,MIN,CATCH_SHOOT_FGM,CATCH_SHOOT_FGA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
defense_stats,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,MIN,STL,BLK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
drives_stats,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,MIN,DRIVES,DRIVE_FGM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
efficiency_stats,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,MIN,POINTS,DRIVE_PTS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
elbowtouch_stats,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,MIN,TOUCHES,ELBOW_TOUCHES,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hustle_stats,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,G,MIN,CONTESTED_SHOTS,CONTESTED_SHOTS_2PT,CONTESTED_SHOTS_3PT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
painttouch_stats,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,MIN,TOUCHES,PAINT_TOUCHES,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
passing_stats,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,MIN,PASSES_MADE,PASSES_RECEIVED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
possessions_stats,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,MIN,POINTS,TOUCHES,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
posttouch_stats,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,MIN,TOUCHES,POST_TOUCHES,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pullupshot_stats,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,MIN,PULL_UP_FGM,PULL_UP_FGA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rebounding_stats,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,MIN,OREB,OREB_CONTEST,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
scoring_splits,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shot_location_stats,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,NICKNAME,RA_FGM,RA_FGA,RA_FG_PCT,PAINT_NON_RA_FGM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
speeddistance_stats,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,MIN,DIST_FEET,DIST_MILES,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
usage_stats,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
collection_summary = []
for name, df in datasets.items():
    collection_summary.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Unique Players": df['PLAYER_ID'].nunique() if 'PLAYER_ID' in df.columns else np.nan,
        "Duplicate Players": df['PLAYER_ID'].duplicated().sum() if 'PLAYER_ID' in df.columns else np.nan
    })
collection_summary = pd.DataFrame(collection_summary)
collection_summary

                Dataset  Rows  Columns  Unique Players  Duplicate Players
0        advanced_stats   582       79             582                  0
1            base_stats   582       69             582                  0
2      catchshoot_stats   582       16             582                  0
3         defense_stats   582       14             582                  0
4          drives_stats   582       25             582                  0
5      efficiency_stats   582       22             582                  0
6      elbowtouch_stats   582       26             582                  0
7          hustle_stats   581       28             581                  0
8      painttouch_stats   582       26             582                  0
9         passing_stats   582       18             582                  0
10    possessions_stats   582       21             582                  0
11      posttouch_stats   582       26             582                  0
12     pullupshot_stats   582       16             582                  0
13     rebounding_stats   578       35             578                  0
14       scoring_splits   582       53             582                  0
15  shot_location_stats   582       30             582                  0
16  speeddistance_stats   582       15             582                  0
17          usage_stats   582       53             582                  0

In [15]:
dataset_inventory_df.to_csv(RAW_DATA_DIR / "01_dataset_inventory.csv", index=False)
column_inventory_df.to_csv(RAW_DATA_DIR / "02_column_inventory.csv", index=False)
collection_summary.to_csv(RAW_DATA_DIR / "03_collection_summary.csv", index=False)